/*
 * MIT License
 *
 * Copyright (c) 2024 Staatsbibliothek zu Berlin - Preußischer Kulturbesitz
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

/**
 * This Set should be immutable - don't add items dynamically
 * The content comes from stripspace.xsl.model of TEI 4.7.0.:
 *   - https://tei-c.org/Vault/P5/4.7.0/xml/tei/odd/
 * For more informationen see
 *   - https://tei-c.org/guidelines/p5/
 *   - https://tei-c.org/release/doc/tei-p5-doc/en/html/ST.html#STGAxs
 */

export const TeiStripSpace = new Set([
  'TEI',
  'abstract',
  'additional',
  'address',
  'adminInfo',
  'altGrp',
  'altIdent',
  'altIdentifier',
  'alternate',
  'analytic',
  'annotation',
  'annotationBlock',
  'app',
  'appInfo',
  'application',
  'arc',
  'argument',
  'att',
  'attDef',
  'attList',
  'availability',
  'back',
  'biblFull',
  'biblStruct',
  'bicond',
  'binding',
  'bindingDesc',
  'body',
  'broadcast',
  'cRefPattern',
  'calendar',
  'calendarDesc',
  'castGroup',
  'castList',
  'category',
  'certainty',
  'char',
  'charDecl',
  'choice',
  'cit',
  'citeStructure',
  'classDecl',
  'classSpec',
  'classes',
  'climate',
  'cond',
  'constraintSpec',
  'content',
  'correction',
  'correspAction',
  'correspContext',
  'correspDesc',
  'custodialHist',
  'dataRef',
  'dataSpec',
  'datatype',
  'decoDesc',
  'dimensions',
  'div',
  'div1',
  'div2',
  'div3',
  'div4',
  'div5',
  'div6',
  'div7',
  'divGen',
  'docTitle',
  'eLeaf',
  'eTree',
  'editionStmt',
  'editorialDecl',
  'elementSpec',
  'ellipsis',
  'encodingDesc',
  'entry',
  'epigraph',
  'epilogue',
  'equipment',
  'event',
  'exemplum',
  'fDecl',
  'fLib',
  'facsimile',
  'figure',
  'fileDesc',
  'floatingText',
  'forest',
  'front',
  'fs',
  'fsConstraints',
  'fsDecl',
  'fsdDecl',
  'fvLib',
  'gap',
  'gi',
  'glyph',
  'graph',
  'graphic',
  'group',
  'handDesc',
  'handNotes',
  'history',
  'hom',
  'hyphenation',
  'iNode',
  'if',
  'imprint',
  'incident',
  'index',
  'interpGrp',
  'interpretation',
  'join',
  'joinGrp',
  'keywords',
  'kinesic',
  'langKnowledge',
  'langUsage',
  'layoutDesc',
  'leaf',
  'lg',
  'linkGrp',
  'list',
  'listAnnotation',
  'listApp',
  'listBibl',
  'listChange',
  'listEvent',
  'listForest',
  'listNym',
  'listObject',
  'listOrg',
  'listPerson',
  'listPlace',
  'listPrefixDef',
  'listRef',
  'listRelation',
  'listTranspose',
  'listWit',
  'location',
  'locusGrp',
  'macroSpec',
  'media',
  'metDecl',
  'model',
  'modelGrp',
  'modelSequence',
  'moduleRef',
  'moduleSpec',
  'monogr',
  'msContents',
  'msDesc',
  'msFrag',
  'msIdentifier',
  'msItem',
  'msItemStruct',
  'msPart',
  'namespace',
  'node',
  'normalization',
  'notatedMusic',
  'noteGrp',
  'notesStmt',
  'nym',
  'object',
  'objectDesc',
  'objectIdentifier',
  'org',
  'paramList',
  'paramSpec',
  'particDesc',
  'performance',
  'person',
  'personGrp',
  'persona',
  'physDesc',
  'place',
  'population',
  'postscript',
  'precision',
  'prefixDef',
  'profileDesc',
  'projectDesc',
  'prologue',
  'publicationStmt',
  'punctuation',
  'quotation',
  'rdgGrp',
  'recordHist',
  'recording',
  'recordingStmt',
  'refsDecl',
  'relatedItem',
  'relation',
  'remarks',
  'respStmt',
  'respons',
  'revisionDesc',
  'root',
  'row',
  'ruby',
  'samplingDecl',
  'schemaRef',
  'schemaSpec',
  'scriptDesc',
  'scriptStmt',
  'seal',
  'sealDesc',
  'segmentation',
  'sequence',
  'seriesStmt',
  'set',
  'setting',
  'settingDesc',
  'sourceDesc',
  'sourceDoc',
  'sp',
  'spGrp',
  'space',
  'spanGrp',
  'specGrp',
  'specList',
  'standOff',
  'state',
  'stdVals',
  'styleDefDecl',
  'subst',
  'substJoin',
  'superEntry',
  'supportDesc',
  'surface',
  'surfaceGrp',
  'table',
  'tagsDecl',
  'taxonomy',
  'teiCorpus',
  'teiHeader',
  'terrain',
  'text',
  'textClass',
  'textDesc',
  'timeline',
  'titlePage',
  'titleStmt',
  'trait',
  'transcriptionDesc',
  'transpose',
  'tree',
  'triangle',
  'typeDesc',
  'unitDecl',
  'unitDef',
  'vAlt',
  'vColl',
  'vDefault',
  'vLabel',
  'vMerge',
  'vNot',
  'vRange',
  'valItem',
  'valList',
  'vocal',
])

/*
  We use head as a key-value component, but in TEI it is a mixed-content node.
  Since the outer slate renders key-value components as blocks, text nodes
  in between remove block nodes.
  Hence we strip head from whitespaces too. This can be avoided by adding a
  domain modell for the key-value components
*/

TeiStripSpace.add('head')
