#maven.installation=
#jdk.installation=
#nodejs.installation=
#report.html.path=build/reports/tests/lcov-report
github.repo=github.com/handschriftenportal-dev/hsp-erfassung
github.user=github_handschriften-dev
#sonar.check=true
#dependency.check=true
