export type Normdatum =
  | 'person'
  | 'koerperschaft'
  | 'ort'
  | 'initium'
  | 'buchkunde'
  | 'buchschmuck'
  | 'schriftart'
  | 'musiknotation'
  | 'einband'
  | 'schreibsprache'
  | 'textgattung'
  | 'ueberlieferungsform'
